FROM node:alpine as build

WORKDIR /usr/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build:docs

FROM nginx:alpine as deploy

COPY --from=build /usr/app/examples/dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf